import { OrthographicCamera } from "@react-three/drei"
import { Canvas, useThree } from "@react-three/fiber"
import { useEffect, useRef, useState } from "react"
import * as THREE from "three"

import { CellsData } from "./interface"
import { IsoMetricGrid } from "./IsoMetricGrid"
import { map_data_cells } from "./map_data"


const GRID_SIZE = { x: 10, y: 10 }
const CELL_SIZE = 12

export function SimpleSim()
{
    const [data, set_data] = useState<CellsData>(map_data_cells)

    return <>
        <Canvas id="scene-3d" style={{ position: "absolute", top: 0, left: 0, width: "100%", height: "100%" }}>
            <SimpleSim3d
                data={data}
                set_data={set_data}
                power_demand={5}
            />
        </Canvas>
    </>
}


interface SimpleSim3dProps
{
    data: CellsData
    set_data: React.Dispatch<React.SetStateAction<CellsData>>
    power_demand: number
}
function SimpleSim3d(props: SimpleSim3dProps)
{
    const sun_ambient_ref = useRef<THREE.AmbientLight>(null)
    const sun_directional_ref = useRef<THREE.DirectionalLight>(null)

    useThree(({ scene }) =>
    {
        scene.background = new THREE.Color(0xeeeeff)
    })

    return <>
        <IsoCamera grid_size={GRID_SIZE} cell_size={CELL_SIZE} />
        <ambientLight ref={sun_ambient_ref} />
        <directionalLight ref={sun_directional_ref} position={[ 15, 5, 7 ]} />

        <IsoMetricGrid size={GRID_SIZE} cell_size={CELL_SIZE} data={props.data} />
    </>
}


/**
 * Orthographic camera positioned at the classic isometric angle (45° yaw, ~35° pitch)
 * so the tile grid fills the view. Adjust `zoom` to scale the view, or replace with
 * OrbitControls + target for interactive panning/zooming.
 * Generated by Claude Sonnet 4.6 - 2026-04-09
 */
function IsoCamera({ grid_size, cell_size }: { grid_size: { x: number, y: number }, cell_size: number })
{
    // Centre of the tile grid in world space (tiles start at origin).
    const cx = (grid_size.x - 1) * cell_size / 2
    const cz = (grid_size.y - 1) * cell_size / 2

    // Distance sized so the whole grid fits in view; (1,1,1) direction = iso angle.
    const dist = Math.max(grid_size.x, grid_size.y) * cell_size * 1.5

    const cam_ref = useRef<THREE.OrthographicCamera>(null)

    useEffect(() =>
    {
        cam_ref.current?.lookAt(cx, 0, cz)
    }, [cx, cz])

    return (
        <OrthographicCamera
            ref={cam_ref}
            makeDefault
            position={[cx + dist, dist, cz + dist]}
            zoom={3}
            near={-dist * 4}
            far={dist * 4}
        />
    )
}
