import { OrthographicCamera } from "@react-three/drei"
import { useEffect, useRef } from "react"
import * as THREE from "three"


/**
 * Orthographic camera positioned at the classic isometric angle (45° yaw, ~35° pitch)
 * so the tile grid fills the view. Adjust `zoom` to scale the view, or replace with
 * OrbitControls + target for interactive panning/zooming.
 * Generated by Claude Sonnet 4.6 - 2026-04-09
 */
interface IsoCameraProps
{
    grid_size: { x: number, y: number }
    cell_size: number
    position_xy?: { x: number, y: number }
}
export function IsoCamera({ grid_size, cell_size, position_xy }: IsoCameraProps)
{
    // Centre of the tile grid in world space (tiles start at origin).
    const cx = (grid_size.x - (position_xy?.x ?? 0)) * cell_size / 2
    const cz = (grid_size.y - (position_xy?.y ?? 0)) * cell_size / 2

    // Distance sized so the whole grid fits in view; (1,1,1) direction = iso angle.
    const dist = Math.max(grid_size.x, grid_size.y) * cell_size * 1.5

    const cam_ref = useRef<THREE.OrthographicCamera>(null)

    useEffect(() =>
    {
        cam_ref.current?.lookAt(cx, 0, cz)
    }, [cx, cz])

    return (
        <OrthographicCamera
            ref={cam_ref}
            makeDefault
            position={[cx + dist, dist, cz + dist]}
            zoom={3}
            near={-dist * 4}
            far={dist * 4}
        />
    )
}
