import { ThreeEvent } from "@react-three/fiber"
import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import * as THREE from "three"

import { Instance, Instances } from "@react-three/drei"
import { CellData, CellsData } from "./interface"
import { IsoMetricGridContentTiles } from "./IsoMetricGridContentTiles"
import { tile_colour } from "./tile"


interface IsoMetricGridProps
{
    size: { x: number, y: number }
    cell_size: number
    data: CellsData
    on_click_tile?: (tile: CellData) => void
    /** Fired with null when the pointer leaves the grid entirely. */
    on_hover_tile?: (tile: CellData | null) => void
}
export function IsoMetricGrid(props: IsoMetricGridProps)
{
    const { size, cell_size, data, on_click_tile, on_hover_tile } = props

    const mesh_ref = useRef<THREE.InstancedMesh>(null)
    const hover_ref = useRef<THREE.Group>(null)
    const [hover_visible, set_hover_visible] = useState(false)


    const tiles = useMemo<CellData[]>(() =>
    {
        const result: CellData[] = []
        for (let y = 0; y < size.y; y++)
        {
            for (let x = 0; x < size.x; x++)
            {
                const cell = data[x]?.[y]
                if (cell) result.push(cell)
            }
        }
        return result
    }, [data, size.x, size.y])


    /**
     * Build a thin box geometry whose face brightness is baked into vertex colours.
     * When MeshBasicMaterial.vertexColors is true, the GPU multiplies instanceColor
     * by the vertex colour, so the top face shows the full tile colour while the
     * side faces appear slightly darker — creating a soft bevel without lighting.
     * Generated by Claude Sonnet 4.6 - 2026-04-09
     *
     * BoxGeometry vertex layout (4 verts per face, never shared):
     *   face 0 = +x   face 1 = -x   face 2 = +y (top)
     *   face 3 = -y   face 4 = +z   face 5 = -z
     */
    const bevel_colors = useMemo(() =>
    {
        const face_brightness = [0.62, 0.62, 1.00, 0.20, 0.72, 0.55]
        const count = 24 // BoxGeometry always has exactly 24 verts (4 per face × 6 faces)
        const colors = new Float32Array(count * 3)
        for (let i = 0; i < count; ++i)
        {
            const b = face_brightness[Math.floor(i / 4)] ?? 0.65
            colors[i * 3    ] = b
            colors[i * 3 + 1] = b
            colors[i * 3 + 2] = b
        }
        return colors
    }, [])
    // const s = cell_size * 0.95    // slight gap visually separates tiles
    const box_geo_s = cell_size * 0.95
    // const h = cell_size * 0.06    // height exposes side faces for the bevel shading
    const box_geo_h = cell_size * 0.1


    const { hover_outline_geo, hover_glow_geo, hover_outline_mat, hover_glow_mat } = useMemo(() =>
    {
        const s = cell_size * 0.97
        const h = cell_size * 0.1
        const box_for_edges = new THREE.BoxGeometry(s, h, s)
        const edges = new THREE.EdgesGeometry(box_for_edges)
        box_for_edges.dispose()
        return {
            hover_outline_geo: edges,
            hover_glow_geo: new THREE.BoxGeometry(s + cell_size * 0.04, h, s + cell_size * 0.04),
            hover_outline_mat: new THREE.LineBasicMaterial({ color: 0xffff44 }),
            hover_glow_mat: new THREE.MeshBasicMaterial({ color: 0xffff44, transparent: true, opacity: 0.12 }),
        }
    }, [cell_size])

    useEffect(() => () =>
    {
        hover_outline_geo.dispose()
        hover_glow_geo.dispose()
        hover_outline_mat.dispose()
        hover_glow_mat.dispose()
    }, [hover_outline_geo, hover_glow_geo, hover_outline_mat, hover_glow_mat])


    const on_click = useCallback((e: ThreeEvent<MouseEvent>) =>
    {
        e.stopPropagation()
        if (e.instanceId === undefined) return
        const tile = tiles[e.instanceId]
        if (tile) on_click_tile?.(tile)
    }, [tiles, on_click_tile])

    const on_pointer_move = useCallback((e: ThreeEvent<PointerEvent>) =>
    {
        if (e.instanceId === undefined) return
        const tile = tiles[e.instanceId]
        if (!tile) return
        if (hover_ref.current)
        {
            hover_ref.current.position.set(tile.x * cell_size, 0, tile.y * cell_size)
        }
        set_hover_visible(true)
        on_hover_tile?.(tile)
    }, [tiles, on_hover_tile, cell_size])

    const on_pointer_leave = useCallback(() =>
    {
        set_hover_visible(false)
        on_hover_tile?.(null)
    }, [on_hover_tile])


    // This is a hack to help minimise the chance of this race condition occuring
    // https://github.com/pmndrs/react-three-fiber/issues/3736
    const [rendered_once, set_rendered_once] = useState(false)
    useEffect(() => set_rendered_once(true))

    return <>
        <Instances
            ref={mesh_ref}
            limit={tiles.length}
        >
            <boxGeometry args={[box_geo_s, box_geo_h, box_geo_s]}>
                <bufferAttribute attach="attributes-color" args={[bevel_colors, 3]} />
            </boxGeometry>
            <meshStandardMaterial vertexColors={true} />
            {tiles.map((cell) =>
            {
                const { x, y } = cell

                return <Instance
                    key={`${x}-${y}`}
                    position={[x * cell_size, 0, y * cell_size]}
                    color={tile_colour(cell)}
                    onClick={on_click_tile ? on_click : undefined}
                    onPointerMove={on_pointer_move}
                    onPointerLeave={on_pointer_leave}
                />
            })}
        </Instances>

        {rendered_once && <IsoMetricGridContentTiles cell_size={cell_size} tiles={tiles} />}

        <group ref={hover_ref} visible={hover_visible}>
            <lineSegments args={[hover_outline_geo, hover_outline_mat]} />
            <mesh args={[hover_glow_geo, hover_glow_mat]} />
        </group>
    </>
}
