import { ThreeEvent } from "@react-three/fiber"
import { useCallback, useEffect, useMemo, useRef } from "react"
import * as THREE from "three"

import { CellsData, LandOrSea } from "./interface"
import { tile_colour } from "./tile"


interface TileInfo
{
    x: number
    y: number
    cell: LandOrSea
}

export interface TileEvent
{
    x: number
    y: number
    cell: LandOrSea
}

interface IsoMetricGridProps
{
    size: { x: number, y: number }
    cell_size: number
    data: CellsData
    on_click_tile?: (tile: TileEvent) => void
    /** Fired with null when the pointer leaves the grid entirely. */
    on_hover_tile?: (tile: TileEvent | null) => void
}
// Generated by Claude Sonnet 4.6 - 2026-04-09
export function IsoMetricGrid(props: IsoMetricGridProps)
{
    const { size, cell_size, data, on_click_tile, on_hover_tile } = props

    const mesh_ref = useRef<THREE.InstancedMesh>(null)


    const tiles = useMemo<TileInfo[]>(() =>
    {
        const result: TileInfo[] = []
        for (let y = 0; y < size.y; y++)
        {
            for (let x = 0; x < size.x; x++)
            {
                const cell = data[x]?.[y]
                if (cell) result.push({ x, y, cell })
            }
        }
        return result
    }, [data, size.x, size.y])


    const { geometry, material } = useMemo(() => {
        return {
            geometry: make_tile_geometry(cell_size),
            material: new THREE.MeshBasicMaterial({ vertexColors: true }),
        }
    }, [cell_size])


    useEffect(() => () =>
    {
        geometry.dispose()
        material.dispose()
    }, [geometry, material])


    // Push instance matrices and colours to the GPU whenever the tile set changes.
    useEffect(() =>
    {
        const mesh = mesh_ref.current
        if (!mesh) return

        const dummy = new THREE.Object3D()
        const color  = new THREE.Color()

        tiles.forEach(({ x, y, cell }, i) =>
        {
            dummy.position.set(x * cell_size, 0, y * cell_size)
            dummy.updateMatrix()
            mesh.setMatrixAt(i, dummy.matrix)
            color.set(tile_colour(cell))
            mesh.setColorAt(i, color)
        })

        mesh.instanceMatrix.needsUpdate = true
        if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true
    }, [tiles, cell_size])

    const on_click = useCallback((e: ThreeEvent<MouseEvent>) =>
    {
        e.stopPropagation()
        if (e.instanceId === undefined) return
        const tile = tiles[e.instanceId]
        if (tile) on_click_tile?.({ x: tile.x, y: tile.y, cell: tile.cell })
    }, [tiles, on_click_tile])

    const on_pointer_move = useCallback((e: ThreeEvent<PointerEvent>) =>
    {
        if (e.instanceId === undefined) return
        const tile = tiles[e.instanceId]
        if (tile) on_hover_tile?.({ x: tile.x, y: tile.y, cell: tile.cell })
    }, [tiles, on_hover_tile])

    const on_pointer_leave = useCallback(() =>
    {
        on_hover_tile?.(null)
    }, [on_hover_tile])

    return (
        <instancedMesh
            ref={mesh_ref}
            args={[geometry, material, tiles.length]}
            onClick={on_click_tile ? on_click : undefined}
            onPointerMove={on_hover_tile ? on_pointer_move : undefined}
            onPointerLeave={on_hover_tile ? on_pointer_leave : undefined}
        />
    )
}


/**
 * Build a thin box geometry whose face brightness is baked into vertex colours.
 * When MeshBasicMaterial.vertexColors is true, the GPU multiplies instanceColor
 * by the vertex colour, so the top face shows the full tile colour while the
 * side faces appear slightly darker — creating a soft bevel without lighting.
 * Generated by Claude Sonnet 4.6 - 2026-04-09
 *
 * BoxGeometry vertex layout (4 verts per face, never shared):
 *   face 0 = +x   face 1 = -x   face 2 = +y (top)
 *   face 3 = -y   face 4 = +z   face 5 = -z
 */
function make_tile_geometry(cell_size: number): THREE.BoxGeometry
{
    const s = cell_size * 0.95    // slight gap visually separates tiles
    const h = cell_size * 0.06    // height exposes side faces for the bevel shading

    const geo = new THREE.BoxGeometry(s, h, s)

    const face_brightness = [0.62, 0.62, 1.00, 0.20, 0.72, 0.55]
    const count = geo.attributes.position!.count   // 24 for a 1-segment box
    const bevel_colors = new Float32Array(count * 3)

    for (let i = 0; i < count; i++)
    {
        const b = face_brightness[Math.floor(i / 4)] ?? 0.65
        bevel_colors[i * 3    ] = b
        bevel_colors[i * 3 + 1] = b
        bevel_colors[i * 3 + 2] = b
    }

    geo.setAttribute("color", new THREE.BufferAttribute(bevel_colors, 3))
    return geo
}
