import { OrthographicCamera } from "@react-three/drei"
import { useFrame, useThree } from "@react-three/fiber"
import { useEffect, useMemo, useRef, useState } from "react"
import * as THREE from "three"

import { uk_land_coverage_simplified } from "../data/land_coverage/uk/data"
import uk_daily_power_demand_profiles from "../data/power_demand/uk/daily_profiles.json"
import { uk_month_hourly_and_location_average_capacity_factor_solar_generation_2018 } from "../data/power_generation/solar_pv"
import { uk_month_hourly_and_location_average_capacity_factor_wind_generation_2018 } from "../data/power_generation/wind_turbine"
import { IsoMetricGrid } from "./IsoMetricGrid"
import { CellsData } from "./interface"
import { map_data_cells } from "./map_data"


const start_datetime = new Date("2018-06-01T00:00:00.000Z")
const speed = 1000 * 60 * 60
const lat_lon = { lat: 50, lon: 0 }

// Grid constants — keep in sync with the IsoMetricGrid props below.
const GRID_SIZE = { x: 20, y: 20 }
const CELL_SIZE  = 12

export function SimpleSim()
{
    const [datetime, set_datetime] = useState(start_datetime)
    const sun_ambient_ref = useRef<THREE.AmbientLight>(null)
    const sun_directional_ref = useRef<THREE.DirectionalLight>(null)

    useThree(({ scene }) =>
    {
        scene.background = new THREE.Color(0xeeeeff)
    })

    useFrame((_state, delta) =>
    {
        const new_datetime = new Date(datetime.getTime() + (delta * speed))
        set_datetime(new_datetime)

        // const sun_args = sun_light_colour_and_intensity_from_datetime_and_latlon(new_datetime, lat_lon, false)
        const sun_args = {
            colour: new THREE.Color(255, 248, 200),
            intensity: 0.0075,
        }
        if (sun_ambient_ref.current)
        {
            sun_ambient_ref.current.color = new THREE.Color(sun_args.colour)
            sun_ambient_ref.current.intensity = sun_args.intensity * 0.5
        }
        if (sun_directional_ref.current)
        {
            sun_directional_ref.current.color = new THREE.Color(sun_args.colour)
            sun_directional_ref.current.intensity = sun_args.intensity
        }
    })

    const data: CellsData = map_data_cells

    // useEffect(() =>
    // {
    //     const map_data_compact = generate_map_data_string(GRID_SIZE)
    //     console.log("data", map_data_compact)
    // }, [GRID_SIZE])

    return <>
        <IsoCamera grid_size={GRID_SIZE} cell_size={CELL_SIZE} />
        <ambientLight ref={sun_ambient_ref} />
        <directionalLight ref={sun_directional_ref} position={[ 15, 5, 7 ]} />

        <IsoMetricGrid size={GRID_SIZE} cell_size={CELL_SIZE} data={data} />
        <Data />
    </>
}



function Data ()
{
    const power_demand = useMemo(() => uk_daily_power_demand_profiles["2010"].average_demand.data, [])
    const wind = useMemo(() => uk_month_hourly_and_location_average_capacity_factor_wind_generation_2018(), [])
    const solar = useMemo(() => uk_month_hourly_and_location_average_capacity_factor_solar_generation_2018(), [])
    const coverage = uk_land_coverage_simplified

    // console.log("coverage", coverage)

    return <></>
}


/**
 * Orthographic camera positioned at the classic isometric angle (45° yaw, ~35° pitch)
 * so the tile grid fills the view. Adjust `zoom` to scale the view, or replace with
 * OrbitControls + target for interactive panning/zooming.
 * Generated by Claude Sonnet 4.6 - 2026-04-09
 */
function IsoCamera({ grid_size, cell_size }: { grid_size: { x: number, y: number }, cell_size: number })
{
    // Centre of the tile grid in world space (tiles start at origin).
    const cx = (grid_size.x - 1) * cell_size / 2
    const cz = (grid_size.y - 1) * cell_size / 2

    // Distance sized so the whole grid fits in view; (1,1,1) direction = iso angle.
    const dist = Math.max(grid_size.x, grid_size.y) * cell_size * 1.5

    const cam_ref = useRef<THREE.OrthographicCamera>(null)

    useEffect(() =>
    {
        cam_ref.current?.lookAt(cx, 0, cz)
    }, [cx, cz])

    return (
        <OrthographicCamera
            ref={cam_ref}
            makeDefault
            position={[cx + dist, dist, cz + dist]}
            zoom={3}
            near={-dist * 4}
            far={dist * 4}
        />
    )
}
